version: '3.8'

networks:
    datapipeline:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "172.18.0.0/16"

services:
  zookeeper-1:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - '2181:2181'  # Corrected port mapping
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      datapipeline:
        ipv4_address: 172.18.0.2


  kafka:
    # container_name: kafka-local-kafka-1
    image: confluentinc/cp-kafka:5.3.1
    depends_on:
      - zookeeper-1
    restart: on-failure
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_LOG_DIRS: /kafka/kafka-logs-1
    networks:
      datapipeline:
        ipv4_address: 172.18.0.3

  mongodb-cont:
    image: mongo:latest
    container_name: mongoDB-Cont
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - '27018:27017'  # Corrected port mapping
    networks:
      datapipeline:
        ipv4_address: 172.18.0.4


  spark-master:
    image: bitnami/spark:latest
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
      - ./consumer.py:/opt/bitnami/spark/anyfilename.py
    depends_on:
      - kafka
    networks:
      datapipeline:
        ipv4_address: 172.18.0.8
    extra_hosts:
      - "kafka:172.18.0.3"

  spark-worker-1:
    image: bitnami/spark:latest
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_MASTER_URL: spark://spark-master:7077
    networks:
      datapipeline:
        ipv4_address: 172.18.0.5

  spark-worker-2:
    image: bitnami/spark:latest
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_MASTER_URL: spark://spark-master:7077
    networks:
      datapipeline:
        ipv4_address: 172.18.0.6


# version: '3.8'

# networks:
#     datapipeline:
#         driver: bridge
#         ipam:
#             driver: default
#             config:
#                 - subnet: "172.18.0.0/16"

# services:
#   zookeeper-1:
#     image: 'bitnami/zookeeper:latest'
#     container_name: zookeeper
#     hostname: zookeeper
#     ports:
#       - '2181:2181'  # Corrected port mapping
#     environment:
#       - ALLOW_ANONYMOUS_LOGIN=yes
#     networks:
#       datapipeline:
#         ipv4_address: 172.18.0.2


#   kafka:
#     image: 'bitnami/kafka:latest'
#     container_name: kafka
#     hostname: kafka
#     ports:
#       - '9092:9092'  # Corrected port mapping
#     environment:
#       # - KAFKA_BROKER_ID=1
#       # - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
#       # - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092  # Use the service name
#       # - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#       # - ALLOW_PLAINTEXT_LISTENER=yes
#       KAFKA_BROKER_ID: 1
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#       KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#       KAFKA_BROKER_ID: 1
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
#       KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#     depends_on:
#       - zookeeper-1  # Simplified depends_on syntax
#     networks:
#       datapipeline:
#         ipv4_address: 172.18.0.3

#   mongodb-cont:
#     image: mongo:latest
#     container_name: mongoDB-Cont
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: 123456
#     ports:
#       - '27018:27017'  # Corrected port mapping
#     networks:
#       datapipeline:
#         ipv4_address: 172.18.0.4


